"""create_reminder_tables

Revision ID: 1654b286a2b9
Revises: 23b5023e0c72
Create Date: 2026-07-24 21:17:59.830795

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '1654b286a2b9'
down_revision: Union[str, None] = '23b5023e0c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('reminder_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_histories_auction_id'), 'reminder_histories', ['auction_id'], unique=False)
    op.create_index(op.f('ix_reminder_histories_member_id'), 'reminder_histories', ['member_id'], unique=False)
    op.create_table('reminder_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.Column('automatic_reminder', sa.Boolean(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_settings_auction_id'), 'reminder_settings', ['auction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_settings_auction_id'), table_name='reminder_settings')
    op.drop_table('reminder_settings')
    op.drop_index(op.f('ix_reminder_histories_member_id'), table_name='reminder_histories')
    op.drop_index(op.f('ix_reminder_histories_auction_id'), table_name='reminder_histories')
    op.drop_table('reminder_histories')
    # ### end Alembic commands ###
