"""add_module_to_audit_logs

Revision ID: 23b5023e0c72
Revises: f6b765e81059
Create Date: 2026-07-19 18:02:56.461068

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '23b5023e0c72'
down_revision: Union[str, None] = 'f6b765e81059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('module', sa.String(length=50), server_default='System', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'module')
    # ### end Alembic commands ###
