"""redefine_auctions

Revision ID: 3be525a58ac6
Revises: adf43cc7bed4
Create Date: 2026-07-19 14:11:59.495137

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '3be525a58ac6'
down_revision: Union[str, None] = 'adf43cc7bed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('winning_month', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_members_auction_id'), 'auction_members', ['auction_id'], unique=False)
    op.create_index(op.f('ix_auction_members_member_id'), 'auction_members', ['member_id'], unique=False)
    op.drop_table('auction_members_placeholder')
    op.add_column('auctions', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('auctions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('auctions', sa.Column('prize_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('auctions', sa.Column('monthly_contribution', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('auctions', sa.Column('total_months', sa.Integer(), nullable=False))
    op.add_column('auctions', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('auctions', sa.Column('current_month', sa.Integer(), nullable=False))
    op.drop_index('ix_auctions_auction_date', table_name='auctions')
    op.drop_index('ix_auctions_auction_number', table_name='auctions')
    op.create_index(op.f('ix_auctions_name'), 'auctions', ['name'], unique=False)
    op.create_index(op.f('ix_auctions_start_date'), 'auctions', ['start_date'], unique=False)

    # Recreate the enum type for status
    op.drop_column('auctions', 'status')
    op.execute("DROP TYPE IF EXISTS auction_status")
    op.execute("CREATE TYPE auction_status AS ENUM ('upcoming', 'active', 'completed', 'cancelled')")
    op.add_column('auctions', sa.Column('status', sa.Enum('upcoming', 'active', 'completed', 'cancelled', name='auction_status'), nullable=False, server_default='upcoming'))

    op.create_index(op.f('ix_auctions_status'), 'auctions', ['status'], unique=False)
    op.drop_constraint('auctions_member_id_fkey', 'auctions', type_='foreignkey')
    op.drop_column('auctions', 'auction_number')
    op.drop_column('auctions', 'amount')
    op.drop_column('auctions', 'member_id')
    op.drop_column('auctions', 'auction_date')
    op.drop_column('members', 'occupation')
    op.drop_column('members', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('occupation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('auctions', sa.Column('auction_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('auctions', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('auctions', sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('auctions', sa.Column('auction_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('auctions_member_id_fkey', 'auctions', 'members', ['member_id'], ['id'], ondelete='SET NULL')
    
    op.drop_index(op.f('ix_auctions_status'), table_name='auctions')
    
    # Revert the enum type for status
    op.drop_column('auctions', 'status')
    op.execute("DROP TYPE IF EXISTS auction_status")
    op.execute("CREATE TYPE auction_status AS ENUM ('scheduled', 'completed', 'cancelled')")
    op.add_column('auctions', sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='auction_status'), nullable=False, server_default='scheduled'))

    op.drop_index(op.f('ix_auctions_start_date'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_name'), table_name='auctions')
    op.create_index('ix_auctions_auction_number', 'auctions', ['auction_number'], unique=True)
    op.create_index('ix_auctions_auction_date', 'auctions', ['auction_date'], unique=False)
    op.drop_column('auctions', 'current_month')
    op.drop_column('auctions', 'start_date')
    op.drop_column('auctions', 'total_months')
    op.drop_column('auctions', 'monthly_contribution')
    op.drop_column('auctions', 'prize_amount')
    op.drop_column('auctions', 'description')
    op.drop_column('auctions', 'name')
    op.create_table('auction_members_placeholder',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name='auction_members_placeholder_member_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='auction_members_placeholder_pkey')
    )
    op.drop_index(op.f('ix_auction_members_member_id'), table_name='auction_members')
    op.drop_index(op.f('ix_auction_members_auction_id'), table_name='auction_members')
    op.drop_table('auction_members')
    # ### end Alembic commands ###
