"""add_is_deleted_to_expenses

Revision ID: 611c8cc8b0a2
Revises: 2d55e2270a9a
Create Date: 2026-07-19 17:25:16.935578

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '611c8cc8b0a2'
down_revision: Union[str, None] = '2d55e2270a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_payments_placeholder')
    op.drop_table('auction_winners_placeholder')
    op.add_column('expenses', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'is_deleted')
    op.create_table('auction_winners_placeholder',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name='auction_winners_placeholder_member_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='auction_winners_placeholder_pkey')
    )
    op.create_table('monthly_payments_placeholder',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name='monthly_payments_placeholder_member_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='monthly_payments_placeholder_pkey')
    )
    # ### end Alembic commands ###
