"""add_member_fields

Revision ID: 97f0915d0bb4
Revises: 
Create Date: 2026-07-19 13:51:50.689865

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '97f0915d0bb4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('age', sa.Integer(), nullable=False))
    op.add_column('members', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('members', sa.Column('occupation', sa.String(length=100), nullable=True))
    op.add_column('members', sa.Column('notes', sa.Text(), nullable=True))
    op.drop_constraint('members_phone_key', 'members', type_='unique')
    op.create_index(op.f('ix_members_phone'), 'members', ['phone'], unique=True)
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.drop_index(op.f('ix_members_phone'), table_name='members')
    op.create_unique_constraint('members_phone_key', 'members', ['phone'])
    op.drop_column('members', 'notes')
    op.drop_column('members', 'occupation')
    op.drop_column('members', 'gender')
    op.drop_column('members', 'age')
    # ### end Alembic commands ###
