"""add_monthly_auction_engine

Revision ID: 9f578fa9148e
Revises: b3a19a084b20
Create Date: 2026-07-19 14:38:39.969558

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '9f578fa9148e'
down_revision: Union[str, None] = 'b3a19a084b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_months',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('month_number', sa.Integer(), nullable=False),
    sa.Column('auction_date', sa.Date(), nullable=True),
    sa.Column('winning_member_id', sa.Integer(), nullable=True),
    sa.Column('bid_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('community_commission', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dividend_per_member', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winning_member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_months_auction_id'), 'auction_months', ['auction_id'], unique=False)
    op.create_index(op.f('ix_auction_months_winning_member_id'), 'auction_months', ['winning_member_id'], unique=False)
    op.create_table('auction_dividends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_month_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('dividend_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_month_id'], ['auction_months.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auction_dividends_auction_month_id'), 'auction_dividends', ['auction_month_id'], unique=False)
    op.create_index(op.f('ix_auction_dividends_member_id'), 'auction_dividends', ['member_id'], unique=False)
    op.create_table('monthly_contributions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_month_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('minimum_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_status', sa.Boolean(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_month_id'], ['auction_months.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_contributions_auction_month_id'), 'monthly_contributions', ['auction_month_id'], unique=False)
    op.create_index(op.f('ix_monthly_contributions_member_id'), 'monthly_contributions', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_contributions_member_id'), table_name='monthly_contributions')
    op.drop_index(op.f('ix_monthly_contributions_auction_month_id'), table_name='monthly_contributions')
    op.drop_table('monthly_contributions')
    op.drop_index(op.f('ix_auction_dividends_member_id'), table_name='auction_dividends')
    op.drop_index(op.f('ix_auction_dividends_auction_month_id'), table_name='auction_dividends')
    op.drop_table('auction_dividends')
    op.drop_index(op.f('ix_auction_months_winning_member_id'), table_name='auction_months')
    op.drop_index(op.f('ix_auction_months_auction_id'), table_name='auction_months')
    op.drop_table('auction_months')
    # ### end Alembic commands ###
