"""member module

Revision ID: adf43cc7bed4
Revises: 97f0915d0bb4
Create Date: 2026-07-19 14:06:03.551118

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'adf43cc7bed4'
down_revision: Union[str, None] = '97f0915d0bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
